### ISSUE TITLE
-a removes configurations that are required

### ISSUE THREAD

**Issue by Iijil1** [FransFaase/SymbolicTM#4]
After running SymbolicTM on a file that was fixed with -a I get "no match" errors, when there weren't any before the fix.

Using -a again shows that it then wants to add new configurations, e.g. 
B: .@0(01)*10011 1 0(10)*1(11)*10@
Looking at the output of the first -a run I find that it commented out a configuration that could be used instead of this new one:
/ Matching B: .@(01)*10011 1 0(10)*1(11)*10@

Thanks a lot for your work on this program! I'm trying to use it to verify the proofs my ctl-decider program produces, so the files can be big and the configurations a bit messy.

[Skelet36.txt](https://github.com/FransFaase/SymbolicTM/files/9739631/Skelet36.txt)
[Skelet36fixed.txt](https://github.com/FransFaase/SymbolicTM/files/9739632/Skelet36fixed.txt)
[Skelet36fixedTwice.txt](https://github.com/FransFaase/SymbolicTM/files/9739633/Skelet36fixedTwice.txt)

**Comment by FransFaase** [comment]
I am going to investigate this. But it might take some time.

**Comment by FransFaase** [comment]
When processing the file Skelet36.txt, I see a lot of error message like:
```
Error: pattern is A: .@(11)*011 0 010@ matches A: .@(00)*011 0 010@
```
At first this looked wrong to me, but it seems okay, because they are both equivalent with: `.@011 0 010@`

The above commit adds to command line options:
* The option -csa cleans rules like `(00)*.@` into `.@`.
* The option -ru removes unused rules from the output when -a is used.

If the original file is processed with the commands:
```
./SymbolicTM -csa -a Skelet36.txt
./SymbolicTM -a Skelet36.txt
```
And next with the following repeated until no warnings about unused rules are reported:
```
./SymbolicTM -ru -a Skelet36.txt
```
It results in the Sketel36.txt file with the commit. I think that this solution could further be reduced because there are many cases of `01(01)*` that could be changed into `(01)+` or even `(01)*` and it seems that there are also some rules that could be combined.

**Comment by Iijil1** [comment]
Thanks, that works!

One could certainly find a simpler set of configurations for Skelet36, but I'm happy that my decider finds something that works at all, especially with parameters that also worked for many other machines in the scan :)

Using more specific parameters I found a shorter proof and was able to clean it up with the new commit. There are presumably still a lot of reductions that could be done, but I don't think that finding those is all that important.

[Skelet36v2.txt](https://github.com/FransFaase/SymbolicTM/files/9745312/Skelet36v2.txt)
